Fix compile error introduced by a439211c1f9826
With semicolon added it fails with,

/opt/kde/include/KF5/KIOWidgets/kdesktopfileactions.h:34:1: error: declaration does not declare anything [-fpermissive]
   34 | KIOWIDGETS_DEPRECATED_VERSION(5, 82, "For lack of usage.");